using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Spectre.Console;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace BitPantry.VirtualConsole.Tests;

/// <summary>
/// Integration tests for VirtualConsole with Spectre.Console.
/// These tests verify that VirtualConsole correctly handles ANSI sequences
/// generated by Spectre.Console's rich rendering features like progress bars.
/// </summary>
[TestClass]
public class SpectreConsoleIntegrationTests
{
    /// <summary>
    /// Tests the complete UX flow for a file upload command:
    /// 
    /// STARTING STATE:
    /// Line 0: sandbox> server upload file.txt /
    /// 
    /// IN PROGRESS STATE (progress bar updates in place):
    /// Line 0: sandbox> server upload file.txt /
    /// Line 1: (blank or progress moves here)
    /// Line 2: Uploading file ----             20%
    /// 
    /// COMPLETED STATE (progress bar cleared, summary on first line after command):
    /// Line 0: sandbox> server upload file.txt /
    /// Line 1: Uploaded x files to y.
    /// Line 2: sandbox>
    /// </summary>
    [TestMethod]
    public async Task SpectreProgress_UploadFlow_ShouldClearProgressAndShowSummary()
    {
        var virtualConsole = new VirtualConsole(80, 24);
        virtualConsole.StrictMode = true;
        var adapter = new BitPantry.VirtualConsole.Testing.VirtualConsoleAnsiAdapter(virtualConsole);
        
        // === STARTING STATE ===
        // Simulate the prompt and command already on screen
        adapter.Write("sandbox> server upload file.txt /");
        adapter.WriteLine(); // Move to next line after command
        
        // Verify starting state
        virtualConsole.GetRow(0).GetText().TrimEnd().Should().Be("sandbox> server upload file.txt /");
        virtualConsole.CursorRow.Should().Be(1);
        
        // === IN PROGRESS STATE ===
        // Run Spectre progress with updates
        await adapter.Progress()
            .AutoClear(true)
            .Columns(
                new TaskDescriptionColumn(),
                new ProgressBarColumn(),
                new PercentageColumn())
            .StartAsync(async ctx =>
            {
                var task = ctx.AddTask("Uploading file.txt");
                task.MaxValue = 100;
                
                // Simulate progress updates
                for (int i = 0; i <= 100; i += 25)
                {
                    task.Value = i;
                    await Task.Delay(10); // Allow renderer to update
                }
            });
        
        // === COMPLETED STATE ===
        // Write summary (should appear on first line after command)
        adapter.WriteLine("Uploaded 1 file to /.");
        
        // Write new prompt
        adapter.Write("sandbox>");
        
        // Dump state for debugging
        var debugInfo = new StringBuilder();
        debugInfo.AppendLine($"=== VirtualConsole Final State ===");
        debugInfo.AppendLine($"Cursor: Row={virtualConsole.CursorRow}, Col={virtualConsole.CursorColumn}");
        for (int i = 0; i < 5; i++)
        {
            var line = virtualConsole.GetRow(i).GetText().TrimEnd();
            debugInfo.AppendLine($"  Line {i}: [{line}]");
        }
        System.Diagnostics.Debug.WriteLine(debugInfo.ToString());
        
        // VERIFY COMPLETED STATE:
        // Line 0: Original command (unchanged)
        virtualConsole.GetRow(0).GetText().TrimEnd().Should().Be("sandbox> server upload file.txt /", debugInfo.ToString());
        
        // Line 1: Summary message (progress bar was cleared, this is first line after command)
        virtualConsole.GetRow(1).GetText().TrimEnd().Should().Be("Uploaded 1 file to /.", debugInfo.ToString());
        
        // Line 2: New prompt
        virtualConsole.GetRow(2).GetText().TrimEnd().Should().Be("sandbox>", debugInfo.ToString());
        
        // Lines 3+ should be empty (no progress bar residue)
        for (int i = 3; i < virtualConsole.Height; i++)
        {
            virtualConsole.GetRow(i).GetText().Trim().Should().BeEmpty($"Line {i} should be empty\n{debugInfo}");
        }
        
        // CRITICAL: No duplicate progress bars anywhere
        var allContent = virtualConsole.GetScreenContent();
        var progressBarCount = Regex.Matches(allContent, "━").Count;
        progressBarCount.Should().Be(0, $"Progress bar should be completely cleared\n{debugInfo}");
    }

    /// <summary>
    /// Tests that multiple progress updates don't leave duplicate progress bars.
    /// This is the key bug we're trying to catch - when progress updates,
    /// each update should overwrite the previous, not add a new line.
    /// </summary>
    [TestMethod]
    public async Task SpectreProgress_MultipleUpdates_ShouldNotLeaveDuplicates()
    {
        var virtualConsole = new VirtualConsole(80, 24);
        virtualConsole.StrictMode = true;
        var adapter = new BitPantry.VirtualConsole.Testing.VirtualConsoleAnsiAdapter(virtualConsole);
        
        // Simulate command prompt
        adapter.WriteLine("sandbox> server upload largefile.bin /");
        
        // Run progress with many rapid updates to trigger the timing issue
        await adapter.Progress()
            .AutoClear(true)
            .Columns(
                new TaskDescriptionColumn(),
                new ProgressBarColumn(),
                new PercentageColumn(),
                new TransferSpeedColumn(),
                new SpinnerColumn())
            .StartAsync(async ctx =>
            {
                var task = ctx.AddTask("Uploading largefile.bin");
                task.MaxValue = 100;
                
                // Many rapid updates to trigger timing issue
                for (int i = 0; i <= 100; i += 5)
                {
                    task.Value = i;
                    await Task.Delay(2); // Fast updates
                }
            });
        
        // Write summary
        adapter.WriteLine("Uploaded largefile.bin to /.");
        adapter.Write("sandbox>");
        
        // Collect lines with content
        var debugInfo = new StringBuilder();
        debugInfo.AppendLine($"=== VirtualConsole State After Progress ===");
        var linesWithContent = new List<(int index, string content)>();
        for (int i = 0; i < virtualConsole.Height; i++)
        {
            var line = virtualConsole.GetRow(i).GetText().TrimEnd();
            if (!string.IsNullOrEmpty(line))
            {
                linesWithContent.Add((i, line));
                debugInfo.AppendLine($"  Line {i}: [{line}]");
            }
        }
        
        // KEY ASSERTION: Should have exactly 3 lines with content
        // Line 0: command, Line 1: summary, Line 2: new prompt
        linesWithContent.Should().HaveCount(3, $"Expected exactly 3 lines (command, summary, prompt), found:\n{debugInfo}");
        
        // No progress bar characters should remain
        var allContent = virtualConsole.GetScreenContent();
        allContent.Should().NotContain("━", $"Progress bar characters should be cleared\n{debugInfo}");
        allContent.Should().NotContain("Uploading", $"Progress status should be cleared\n{debugInfo}");
    }

    /// <summary>
    /// Tests an instant completion (no updates) - simplest case.
    /// </summary>
    [TestMethod]
    public async Task SpectreProgress_InstantCompletion_ShouldShowCleanSummary()
    {
        var virtualConsole = new VirtualConsole(80, 24);
        virtualConsole.StrictMode = true;
        var adapter = new BitPantry.VirtualConsole.Testing.VirtualConsoleAnsiAdapter(virtualConsole);
        
        // Command
        adapter.WriteLine("sandbox> server upload small.txt /");
        
        // Instant progress (no updates, immediately complete)
        await adapter.Progress()
            .AutoClear(true)
            .Columns(
                new TaskDescriptionColumn(),
                new ProgressBarColumn(),
                new PercentageColumn())
            .StartAsync(async ctx =>
            {
                var task = ctx.AddTask("Uploading small.txt");
                task.MaxValue = 100;
                task.Value = 100; // Immediately complete
                await Task.CompletedTask;
            });
        
        // Summary and new prompt
        adapter.WriteLine("Uploaded small.txt to /.");
        adapter.Write("sandbox>");
        
        // Dump state
        var debugInfo = new StringBuilder();
        debugInfo.AppendLine($"=== VirtualConsole State ===");
        for (int i = 0; i < 5; i++)
        {
            var line = virtualConsole.GetRow(i).GetText().TrimEnd();
            debugInfo.AppendLine($"  Line {i}: [{line}]");
        }
        System.Diagnostics.Debug.WriteLine(debugInfo.ToString());
        
        // Verify clean state
        virtualConsole.GetRow(0).GetText().TrimEnd().Should().Be("sandbox> server upload small.txt /", debugInfo.ToString());
        virtualConsole.GetRow(1).GetText().TrimEnd().Should().Be("Uploaded small.txt to /.", debugInfo.ToString());
        virtualConsole.GetRow(2).GetText().TrimEnd().Should().Be("sandbox>", debugInfo.ToString());
        
        // No progress residue
        virtualConsole.GetRow(3).GetText().Trim().Should().BeEmpty(debugInfo.ToString());
    }
}
