name: Build and Deploy Server Package

on:
  push:
    tags:
      - 'remote-signalr-v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history
        ref: ${{ github.ref }}  # Ensures the correct ref is checked out

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '5.12.0'

    - name: Determine version
      id: gitversion
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/remote-signalr-v}
        echo "VERSION=$TAG_VERSION" >> $GITHUB_ENV

    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore --no-cache --force

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --configuration Release --verbosity normal --logger trx

    - name: Pack BitPantry.CommandLine.Remote.SignalR
      run: dotnet pack ./BitPantry.CommandLine.Remote.SignalR/BitPantry.CommandLine.Remote.SignalR.csproj --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ env.VERSION }} -p:UseProjectReferences=false

    - name: Publish BitPantry.CommandLine.Remote.SignalR to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json